apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ApprovedRegistries
metadata:
  name: approved-registries
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["flask-app"]
  parameters:
    registries:
      - "flask-app"
      - "384713541270.dkr.ecr.us-east-1.amazonaws.com"
      - "nginx"