apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockRootContainers
metadata:
  name: block-root-containers
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["flask-app"]